apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-dextrusweb-deploy
  labels:
    app: {{ .Values.name }}-dextrusweb
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-dextrusweb
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-dextrusweb
    spec:
      containers:
        - name: {{ .Values.name }}-dextrusweb
          image: {{ .Values.image.dextruswebImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: efs-pvc
              mountPath: "/assets"
            - name: dextrus-config-maps
              mountPath: "/home/dbexplorer/resources/"
              readOnly: true
          command:
            - /bin/bash
            - -c
            - |
              java -jar /home/dextrusweb/app.jar --spring.config.location="/home/dextrusweb/resources/"
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: {{ .Values.name }}-dextrusweb-appdev-cm
            - configMap:
                name: application-cm
            - configMap:
                name: hive-site-cm
            - configMap:
                name: metastore-site-cm
