apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-streaming-deploy
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name }}-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-streaming
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-streaming
    spec:
      containers:
      - name: streaming
        image: {{ .Values.image.streamingImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
