apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-twitter-deploy
  namespace: {{ .Values.namespace | default "default"}}
  labels:
    app: {{ .Values.name }}-twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-twitter
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-twitter
    spec:
      containers:
        - name: {{ .Values.name }}-twitter
          image: {{ .Values.image.twitterImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: dextrus-config-maps
              mountPath: "/home/twitter/resources"
              readOnly: true
      volumes:
        - name: dextrus-config-maps
          projected:
            sources:
            - configMap:
                name: {{ .Values.name }}-twitter-appdev-cm                    
            - configMap:
                name: application-cm

