apiVersion: v1
kind: Service
metadata:
  name: streaming-headless-svc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: streaming
  ports:
    - protocol: TCP
      port: 44103
  clusterIP: None

